/// <reference types="Cypress" />

it('navigation', () => {
  cy.visit('https://github.com/')
  cy.viewport(1300, 660)
  //Why GitHub?
  cy.contains('Why GitHub?').should('be.visible')
 .get('details').eq('0').invoke('attr', 'open', 'true')
  cy.get('a[data-ga-click$="Features"]')
  .should('be.visible').and('include.text','Features')
  //Team
  cy.get('a[data-ga-click$="Team"]')
  .should('be.visible').and('have.text', 'Team')
  cy.get('a[data-ga-click$="Enterprise"]')
  .should('be.visible').and('have.text', 'Enterprise')
  //Explore
  cy.contains('Explore').should('be.visible')
  .get('details').eq('1').invoke('attr', 'open', 'true')
  cy.get('a[data-ga-click$="Explore"]')
  .should('be.visible').and('include.text','Explore')
  cy.get('a[data-ga-click$="Topics"]')
  .should('be.visible').and('include.text','Topics')
  cy.get('a[data-ga-click$="Collections"]')
  .should('be.visible').and('include.text','Collections')
  cy.get('a[data-ga-click$="Trending"]')
  .should('be.visible').and('include.text','Trending')
  cy.get('a[data-ga-click$="Learning lab"]')
  .should('be.visible').and('include.text','Learning Lab')
  //Marketplace
  cy.get('a[data-ga-click$="Marketplace"]')
  .should('be.visible').and('have.text', 'Marketplace')
  //Pricing
  cy.contains('Pricing').should('be.visible')
 .get('details').eq('2').invoke('attr', 'open', 'true')
  cy.get('a[data-ga-click$="Pricing"]')
  .should('be.visible').and('include.text','Plans ')
  cy.get('a[data-ga-click$="Compare plans"]')
  .should('be.visible').and('include.text','Compare plans')
  cy.get('a[data-ga-click$="Contact Sales"]')
  .should('be.visible').and('include.text','Contact Sales')
  cy.get('a[data-ga-click$="Education"]')
  .should('be.visible').and('include.text','Education')
})

it('check dropdown for Why GitHub', () => {
  cy.get('li[class="edge-item-fix"]')
  .find('a').eq('0').should('include.text','Mobile')
  cy.get('li[class="edge-item-fix"]')
  .find('a').eq('1').should('include.text','Actions')
  cy.get('li[class="edge-item-fix"]')
  .find('a').eq('2').should('include.text','Codespaces')
  cy.get('li[class="edge-item-fix"]')
  .find('a').eq('3').should('include.text','Packages')
  cy.get('li[class="edge-item-fix"]')
  .find('a').eq('4').should('include.text','Security')
  cy.get('li[class="edge-item-fix"]')
  .find('a').eq('5').should('include.text','Code review')
  cy.get('li[class="edge-item-fix"]')
  .find('a').eq('6').should('include.text','Issues')
  cy.get('li[class="edge-item-fix"]')
  .find('a').eq('7').should('include.text','Integrations')
  cy.get('li[class="edge-item-fix"]')
  .find('a').eq('8').should('include.text','GitHub Sponsors')
  cy.get('li[class="edge-item-fix"]')
  .find('a').eq('9').should('include.text','Customer stories')
})
